package dev.tsp;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

// The main class — TSP stands for Travelling Salesman Problem
public class TSP {

    public record City(String name, double x, double y){
    // A "record" is a compact class that just holds data.
    // Every City automatically gets: a constructor, getters (name(), x(), y()),
    // equals(), hashCode(), and toString() — all generated by Java.
    // 'name' is the city label, 'x' and 'y' are its coordinates on a 2D plane.
        double distanceTo(City other){
        // Method that calculates straight-line distance from THIS city to another one
            double dx = this.x -other.x;
            // Horizontal gap between the two cities (can be negative, doesn't matter)
            double dy = this.y -other.y;
            // Vertical gap between the two cities
            return Math.sqrt(dx * dx + dy * dy);
            // Pythagorean theorem: distance = √(dx² + dy²)
            // This gives the straight-line ("as the crow flies") distance
        }
    }

    public static List<City> nearestNeighbour(List<City> cities, int startIndex){
    // Greedy algorithm: always go to the closest unvisited city next.
    // Returns the complete tour as an ordered list of City objects.
    // 'cities'     — the full list of cities to visit
    // 'startIndex' — which city in that list we start from


        int n = cities.size();
        // How many cities there are — used as the loop bound throughout

        boolean[] visited = new boolean[n];
        // One slot per city. false = not yet visited, true = already in the tour.
        // Java initialises all booleans to false automatically.

        List<City> tour = new ArrayList<>();
        // The route we're building — cities get added in visit order

        int current = startIndex;
        // Index of whichever city we're currently standing in
        visited[current] = true;
        // Mark the starting city as visited so we don't return to it
        tour.add(cities.get(current));
        // Add the starting city as the first stop in the tour

        for (int step = 1; step < n; step ++){
        // Repeat (n-1) times — we already placed the start, so we need n-1 more cities
            double bestDist = Double.MAX_VALUE;
            // The shortest distance found so far this step.
            // Starts at the largest possible double so any real distance beats it.
            int next = -1;
            // Index of the best candidate city found so far. -1 = "none found yet"

            for (int i = 0;i < n ;i++){
            // Check every city as a potential next stop
                if(!visited[i]){
                // Only consider cities we haven't been to yet
                    double d = cities.get(current).distanceTo(cities.get(i));
                    // Calculate the distance from our current city to candidate city i
                    if(d < bestDist){
                    // If this candidate is closer than any we've checked so far...
                        bestDist = d ;
                        // ...update the best distance found
                        next = i;
                        // ...and remember this city as our current best candidate
                    }
                }
            }
            visited[next] = true;
            // We've chosen city 'next' — mark it visited so we skip it in future steps
            tour.add(cities.get(next));
            // Append it to the tour
            current = next;
            // Move to that city — it becomes our new starting point for the next step
        }
        tour.add(cities.get(startIndex));
        // Add the starting city again at the end to close the loop (return home)
        return tour;
        // Hand back the completed route
    }

    public static List<City> heldKarp(List<City> cities) {
    // Exact algorithm using dynamic programming — guaranteed to find the shortest tour.
    // Much slower than greedy (exponential time), but optimal.
        int n = cities.size();
        // Number of cities
        double[][] dist = new double[n][n];
        // n×n table: dist[i][j] will hold the distance from city i to city j
        for (int i = 0; i < n; i++){
            for (int j = 0; j < n; j++) {
                dist[i][j] = cities.get(i).distanceTo(cities.get(j));
                // Pre-compute every pair's distance once and store it.
                // Avoids recalculating the same distance hundreds of times later.
            }
        }
        double[][] dp = new double[1 << n][n];
        // The core DP table. Size: 2^n rows × n columns.
        // dp[mask][i] = cheapest cost to have visited exactly the cities
        //               encoded in 'mask', ending at city i.
        //
        // 'mask' is a bitmask: each bit position represents one city.
        // e.g. with 4 cities, mask=0101 (decimal 5) means cities 0 and 2 were visited.
        // 1<<n shifts 1 left by n bits, giving 2^n — the total number of subsets.

        int[][] parent = new int[1<< n][n];
        // Stores WHERE WE CAME FROM for each state.
        // parent[mask][i] = the city we were at before arriving at city i
        //                   when the visited set was 'mask'.
        // Used at the end to reconstruct the actual route.

        for(double[] row : dp) Arrays.fill(row, Double.MAX_VALUE / 2);
        // Initialise every dp entry to "infinity" (we use half of MAX_VALUE
        // to avoid overflow when we later add distances to it).
        // Means "this state has not been reached yet".
        for(int [] row : parent) Arrays.fill(row, -1);
        // Initialise every parent entry to -1 meaning "no predecessor known yet"

        dp[1][0] = 0;
        // Base case: we start at city 0, having visited only city 0.
        // mask=1 in binary is ...0001 — only bit 0 is set, meaning only city 0 visited.
        // Cost is 0 because we haven't travelled anywhere yet.

        for (int mask = 1; mask < (1 << n); mask++){
        // Iterate over every possible subset of cities (every possible bitmask)
            if((mask & 1) == 0) {
            // Skip any subset that doesn't include city 0.
            // (mask & 1) checks bit 0. If it's 0, city 0 isn't in this subset.
            // All valid routes start at city 0, so it must always be included.
                continue;
            }
            for (int u = 0; u < n; u++){
            // For each city u, ask: "are we currently at u in this subset?"
                if((mask & (1 << u)) == 0){
                // (mask & (1<<u)) checks whether bit u is set in mask.
                // If it's 0, city u isn't in this subset — skip it.
                    continue;
                }
                if (dp[mask][u] == Double.MAX_VALUE / 2){
                // If this state was never reached (still "infinity"), skip it —
                // there's no valid path here to extend.
                    continue;
                }
                for(int v = 0; v < n; v++){
                // Try extending the route by visiting one more city v

                    if((mask & (1 << v))!= 0){
                    // If bit v IS set, city v is already visited — skip it.
                    // We only want to go somewhere new.
                        continue;
                    }
                    int nextMask = mask | (1 << v);
                    // Set bit v in the mask to mark city v as now visited.
                    // The OR operation adds v to the visited set without changing others.
                    double newCost = dp[mask][u] + dist[u][v];
                    // Cost of this route = cost to reach u + distance from u to v
                    if (newCost < dp[nextMask][v]){
                    // If this is cheaper than any previously found way to reach v
                    // with this exact set of visited cities.
                        dp[nextMask][v] = newCost;
                        // ...record the new best cost
                        parent[nextMask][v] = u ;
                        // ...and remember that we arrived at v from u
                    }
                }
            }
        }

        int fullMask = (1 << n ) - 1 ;
        // All bits set = all cities visited.
        // e.g. with 4 cities: 1111 in binary = 15 in decimal.
        double best = Double.MAX_VALUE;
        int last = -1;
        // 'last' will hold the index of the best city to end at before going home
        for (int u = 1; u < n ;u++){
        // Check each city (except city 0) as a potential final stop
            double cost = dp[fullMask][u] + dist[u][0];
            // Total cost = cheapest way to visit all cities ending at u
            //            + distance from u back to city 0 (home)
            if(cost < best){
                best = cost;
                // Update the best total tour cost found

                last = u;
                // Remember which city to end at

            }
        }

        List<City> tour = new ArrayList<>();
        // The list we'll fill with the optimal route, in order
        int mask = fullMask;
        // Start reconstruction from the "all cities visited" state
        int cur = last;
        // Start from the last city (just before returning home)
        while ( cur != -1){
            // Walk backwards through parent[] until we hit -1 (no more predecessors = we're at the start)
            tour.add(0, cities.get(cur));
            // Prepend city 'cur' to the tour.
            // We prepend (insert at index 0) because we're walking BACKWARDS —
            // prepending reverses the order back to forward.
            int prev = parent[mask][cur];
            // Look up which city we came from to reach 'cur' in this state
            mask ^= (1 << cur);
            // Remove city 'cur' from the visited set using XOR.
            // XOR flips bit 'cur' from 1 to 0, stepping back to the previous state.

            cur = prev ;
        }
        tour.add(cities.get(0));
        // Append city 0 at the end to close the loop (return home)
        return tour;
        // Return the optimal route
    }

    public static double tourLength(List<City> tour){
    // Utility method: adds up the total distance of a completed tour

        double total = 0;
        // Running sum, starts at zero
        for(int i = 0; i < tour.size() -1; i++ ){
        // Visit every consecutive pair of cities in the tour.
        // We stop at size()-1 because we read tour[i] and tour[i+1] together —
        // going to size() would make tour[i+1] go out of bounds.
            total += tour.get(i).distanceTo(tour.get(i + 1));
            // Add the distance between this city and the next one
        }
        return total;
        // The total travel distance for the whole tour
    }

}
